version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "vcatak-main-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8vazr433is4p"
s3_prefix = "vcatak-main-app"
region = "us-east-1"
profile = "vcatak-main"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "AWSEnvironment=\"dev\""
confirm_changeset = true
image_repositories = []
