AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  NestedCF

  Sample SAM Template for NestedCF

Parameters:

  AWSEnvironment:
    Description: App environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    ConstraintDescription: "Please specify the environment [ dev | test | prod ]"

Mappings:
  Environment:
    dev:
      DeploymetPrefix: vcatak-application
      AdminEmail: vcatak@iolap.com
    test:
      DeploymetPrefix: vcatak-application
      AdminEmail: vcatak@iolap.com
    prod:
      DeploymetPrefix: vcatak-application
      AdminEmail: vcatak@iolap.com


Resources:

  ### SSM Parameters for nested CF templates

  AdminEmailParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${AWSEnvironment}/adminEmail"
      Description: Applications deployment prefix
      Tier: Standard
      Type: String
      Value: !FindInMap [ Environment , !Ref AWSEnvironment, AdminEmail]


  ### SSM Parameter for lambda functions ###

#  SSMSystemParameters:
#    Type: AWS::SSM::Parameter
#    Properties:
#      Name: !Join ["/", [ !Ref DeploymentNamePrefix,  "ApplicationParameters"]]
#      Type: String
#      Value: !Sub
#        "{
#          	\"GENERAL\": {
#          		\"Environment\": \"${Environment}\",
#          		\"DeploymentNamePrefix\": \"${DeploymentNamePrefix}\"
#          	}
#          }"

  VcatakCognitoPoolStack:
    DependsOn: AdminEmailParameter
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/COGNITO.yaml
      Parameters:
        Environment: !Ref AWSEnvironment
        DeploymentPrefix: !FindInMap [ Environment , !Ref AWSEnvironment, DeploymetPrefix]
        AdminEmail: !Sub "/${AWSEnvironment}/adminEmail"

  VcatakAPIStack:
    DependsOn: VcatakCognitoPoolStack
    Type: AWS::Serverless::Application
    Properties:
      Location: templates/API.yaml
      Parameters:
        UserPoolId:
          Fn::GetAtt: [ VcatakCognitoPoolStack, Outputs.UserPoolId ]
#          Fn::ImportValue: !Join [":", [
#            !FindInMap [ Environment , !Ref AWSEnvironment, DeploymetPrefix],
#            "UserPoolId"
#          ]]
        Audience:
          Fn::GetAtt: [ VcatakCognitoPoolStack, Outputs.UserPoolClientId ]
#          Fn::ImportValue: !Join [":", [
#            !FindInMap [ Environment , !Ref AWSEnvironment, DeploymetPrefix],
#            "UserPoolClientId"
#          ]]